### PR TITLE
BLOG: add shapefiles post

### PR DESCRIPTION
**Pull request by nvkelso**
Todos:

- [x] Shapefile downloads are live (Friday April 21st, 2023)
- [x] Spelunker edit links goes live?
- [x] Add screenshots to one off editing section
- [x] Fill in examples in final "bulk editing" section
- [x] Figure out announce email list
- [x] Figure out discussion email list
- [x] What is our contact email for the project? Point to Mapstadon instead...

_NOTE: This initial release of Shapefiles is built once, but in the next two weeks will be automated for any WOF change to rebuild them. We'll also add support for postalcodes and constituencies in that time._

### CODE REVIEW

**Comment by thisisaaronland** [comment]
@nvkelso Is this ready to go?

**Comment by nvkelso** [comment]
Yes!?

We were holding it for the Spelunker link to go live, which I think happened... May 9th? How time flies when we're all busy.

I think the date needs to shift to May 31st instead of April something in the file paths and post metadata?

And then some makefile commands need to be run?

**Comment by nvkelso** [comment]
> I think the date needs to shift to May 31st instead of April something in the file paths and post metadata?

This is done.

Over to you @thisisaaronland for final launch sequence... Which can happen anytime today?

**Comment by thisisaaronland** [comment]
It will happen later tonight or tomorrow morning, yes.

**Comment by thisisaaronland** [comment]
https://whosonfirst.org/blog/2023/05/31/shapefiles/

Closing this without merging. For reasons too dull to get in to here I just merged this by hand, in `main`, locally. I made a hand full of cosmetic changes to add inline CSS to account for tables and lists.

It's live now.

**Pull request closed without merging**
